### ISSUE TITLE
Error trying to add the plugin on Fedora 31

### ISSUE THREAD

**Issue by marvinhosea** [yoannfleurydev/insomnia-plugin-night-owl-theme#1] opened 2020-02-21 23:59 UTC
**Describe the bug**
Trying to install the plugin on 7.1.1 causes an error

**To Reproduce**
1. Go to preference
2. Click on plugins
3. Add `insomnia-plugin-night-owl-theme`
4. Click on install it fails to install

**Expected behavior**
Yarn error /snap/insomnia/62/insomnia: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

**Comment by yoannfleurydev** [comment] 2020-02-22 16:44
Hi, thanks for opening this issue. 👍 
I cannot reproduce the bug on Fedora 31 (using AppImage and not Snap installation as you did).
It looks like an Insomnia error to me, and not a bug related to this plugin. AFAIK, there are two issues that are related to this problem:

- https://github.com/Kong/insomnia/issues/1648
- https://github.com/Kong/insomnia/issues/905

The solution at the moment is to manually install the plugin. 😔

I'm closing this issue. Feel free to open a new one if there is a bug related to this repository. 😃 

Have a nice day.

**Closed as completed by yoannfleurydev** 2020-02-22 16:44 UTC
Labels: wontfix
